---
- name: TEST SECURITY RULE MATCH
  hosts: firewall
  connection: local
  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"
  vars_files:
    - flow-to-match.yml

  tasks:
    - name: Check security rules
      paloaltonetworks.panos.panos_match_rule:
        provider: '{{ device }}'
        vsys: "{{ item.vsys | default(omit) }}"
        source_ip: "{{ item.source_ip }}"
        source_zone: "{{ item.source_zone | default(omit) }}"
        destination_ip: "{{ item.destination_ip }}"
        destination_zone: "{{ item.destination_zone | default(omit) }}"
        application: "{{ item.application }}"
        destination_port: "{{ item.destination_port }}"
        protocol: "{{ item.protocol }}"
      register: result
      loop: "{{ flow_to_match }}"

    - name: Commit output
      ansible.builtin.debug:
        msg: "{{ item.rule }}"
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.rule.name }}"
